// svelte/src/components/componentNote.svelte
<script lang="ts">
  import { invoke } from '@tauri-apps/api/core';
  import { OverlayScrollbarsComponent } from 'overlayscrollbars-svelte';
  import { slide } from 'svelte/transition';
  import ComponentNote from './componentNote.svelte';
  import { cubicInOut } from 'svelte/easing';
  import { dndzone, type DndEvent, type Item as DndItem } from 'svelte-dnd-action';

  import type { Note } from '../types/types';
  import 'overlayscrollbars/overlayscrollbars.css';
  import '../routes/app.css';

  let {
    note,
    reloadNotes,
    setStatus,
    notes,
    noteOpenStates = $bindable<Record<number, boolean>>()
  }: {
    note: Note;
    reloadNotes: () => void;
    setStatus: (msg: string) => void;
    notes: Note[];
    noteOpenStates: Record<number, boolean>;
  } = $props();

  let childNotes = $state<Note[]>([]);
  let previewChildNotes = $state<Note[] | null>(null);

  $effect(() => {
    childNotes = notes.filter(n => n.parent_id === note.id).sort((a, b) => (a.order_id ?? 0) - (b.order_id ?? 0))
  });

  let open = $derived(noteOpenStates[note.id] ?? true);

  let isEditing = $state<boolean>(false);
  let editingTitle = $state('');
  let editingContent = $state('');

  const isCategory = note.note_type === 'categorical';

  let originalOpenState = false;
  let hasSavedState = false;

  let collapseOpen = $derived(isEditing || open);

  async function addChild() {
    try {
      const newNote = await invoke<typeof note>('create_note', { title: 'Untitled', content: '', tabId: note.tab_id, noteType: 'basic', parentId: note.id });
      noteOpenStates = { ...noteOpenStates, [newNote.id]: true };

      await reloadNotes();

      setStatus("Added sub-note successfully");
    } catch (error) {
      console.error("Failed to add sub-note:", error);
      setStatus(`Failed to add sub-note: ${error}`);
    }
  }

  function startEdit() {
    originalOpenState = open;
    hasSavedState = true;
    isEditing = true;
    editingTitle = note.title;
    editingContent = note.content;
  }

  async function saveEdit() {
    try {
      await invoke('update_note', { id: note.id, title: editingTitle, content: editingContent || '' });

      isEditing = false;
      noteOpenStates = { ...noteOpenStates, [note.id]: true };

      await reloadNotes();

      setStatus(`Updated note ${note.title} successfully`);
    } catch (error) {
      console.error('update_note failed:', error);
      setStatus(`Failed to update note: ${error}`);
    }
  }

  function cancelEdit() {
    isEditing = false;

    if (hasSavedState) {
      noteOpenStates = { ...noteOpenStates, [note.id]: originalOpenState };
      hasSavedState = false;
    }
  }

  async function removeNote() {
    try {
      await invoke('delete_note', { id: note.id });

      await reloadNotes();

      setStatus(`Deleted note ${note.title} successfully`);
    } catch (error) {
      console.error('delete_note failed:', error);
      setStatus(`Failed to delete note: ${error}`);
    }
  }

  function insertNewLineAtCursor(textarea: HTMLTextAreaElement) {
    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const value = textarea.value;

    textarea.value = value.slice(0, start) + '\n' + value.slice(end);

    textarea.selectionStart = textarea.selectionEnd = start + 1;

    textarea.dispatchEvent(new Event('input'));
  }

  function clickOutside(node: HTMLElement) {
    const handleClick = (event: MouseEvent) => {
      if (isEditing && node && !node.contains(event.target as Node)) {
        saveEdit();
      }
    };
    document.addEventListener('click', handleClick, true);

    return {
      destroy() {
        document.removeEventListener('click', handleClick, true);
      }
    };
  }

  function toggle() {
    const isOpen = !(noteOpenStates[note.id] ?? true);
    noteOpenStates[note.id] = isOpen;
  }

  let pendingChildNoteUpdate: { ids: number[]; tabId: number | null; parentId: number } | null = null;
  let areChildNotesSyncing = false;

  function handleDnd(e: CustomEvent<DndEvent<DndItem>>) {
    previewChildNotes = [...e.detail.items] as Note[];
  }

  function handleDndFinalize(e: CustomEvent<DndEvent<DndItem>>) {
    previewChildNotes = null;
    const newItems = [...e.detail.items];
    const orderedIds = newItems.map(n => n.id);

    pendingChildNoteUpdate = { ids: orderedIds, tabId: note.tab_id, parentId: note.id };

    if (!areChildNotesSyncing) {
      processPendingChildNoteUpdate();
    }
  }

  async function processPendingChildNoteUpdate() {
    if (!pendingChildNoteUpdate) {
      areChildNotesSyncing = false;
      return;
    }

    areChildNotesSyncing = true;

    const currentBatch = pendingChildNoteUpdate;
    pendingChildNoteUpdate = null;

    let attempt = 0;
    const maxRetries = 3;

    while (attempt <= maxRetries) {
      try {
        await invoke('reorder_notes', { noteIds: currentBatch.ids, tabId: currentBatch.tabId, parentId: currentBatch.parentId });

        setStatus('Sub-notes reordered successfully');
        break;
      } catch (error) {
        console.error("Failed to reorder sub-notes:", error);

        if (attempt >= maxRetries) {
          await reloadNotes();
          setStatus(`Failed to reorder sub-notes! Retrying. Error: ${error}`);
          break;
        }
        await new Promise(r => setTimeout(r, 200 * Math.pow(2, attempt)));
        attempt++;
      }
    }

    areChildNotesSyncing = false;
    processPendingChildNoteUpdate();
  }

  function transformElement(element: HTMLElement | undefined) {
    if (element) {
      element.style.outline = '#723fffd0 solid 2px';
      element.style.zIndex = '1000';
    }
  }

</script>

<div
  class="note"
  class:category={isCategory}
  class:editing={isEditing}
  role="article"
  ondblclick={e => { e.stopPropagation(); startEdit(); }}
  use:clickOutside
>
  <div id="noteTitleBox">
    <small>Last edited: {note.updated_at}</small>
    <small>Note ID: {note.id}</small>
    <small>Tab ID: {note.tab_id}</small>
    <small>Order ID: {note.order_id}</small>
    <small>Parent ID: {note.parent_id}</small>
    <div id="noteControls">
      {#if isCategory}
        <button onclick={toggle} ondblclick={e => { e.stopPropagation(); }} disabled={isEditing}>{open ? 'Hide' : 'Show'}</button>
        <button onclick={addChild} ondblclick={e => { e.stopPropagation(); }}>Add Note</button>
        <button onclick={startEdit} ondblclick={e => { e.stopPropagation(); }}>Edit</button>
        <button onclick={removeNote} ondblclick={e => { e.stopPropagation(); }}>Delete</button>
      {:else if !isCategory}
        <button onclick={toggle} ondblclick={e => { e.stopPropagation(); }} disabled={isEditing}>{open ? 'Hide' : 'Show'}</button>
        <button onclick={startEdit} ondblclick={e => { e.stopPropagation(); }}>Edit</button>
        <button onclick={removeNote} ondblclick={e => { e.stopPropagation(); }}>Delete</button>
      {/if}
    </div>
    {#if isEditing}
      <input
        bind:value={editingTitle}
        placeholder="Title | Enter to save"
        onkeydown={(e) => {
          if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            saveEdit();
          } else if (e.key === 'Escape') {
            cancelEdit();
          }
        }}
      />
    {:else}
      <h3 class="noteTitle">{note.title || 'Untitled'}</h3>
    {/if}
  </div>
  <OverlayScrollbarsComponent options={{ scrollbars: {autoHide: 'move' as const, autoHideDelay: 800, theme: 'os-theme-dark'}, overflow: { x: "hidden" } }}>
    <div id="noteContentOuter">
      {#if collapseOpen}
        <div style="overflow: hidden;" transition:slide={{ delay: 100, duration: 400, easing: cubicInOut }}>
          {#if isEditing}
            {#if !isCategory}
              <textarea
                bind:value={editingContent}
                placeholder="Enter to save | Shift+Enter for new line | Esc to cancel"
                rows="16"
                onkeydown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    saveEdit();
                  } else if (e.key === 'Enter' && e.shiftKey) {
                    e.preventDefault();
                    insertNewLineAtCursor(e.currentTarget);
                  } else if (e.key === 'Escape') {
                    cancelEdit();
                  }
                }}
              >
              </textarea>
              <div class="edit-actions">
                <button onclick={saveEdit}>Save</button>
                <button onclick={cancelEdit}>Cancel</button>
                <small>Press Esc to cancel | Press Enter or click outside to save</small>
              </div>
            {:else if isCategory}
              <div class="edit-actions">
                <button onclick={saveEdit}>Save</button>
                <button onclick={cancelEdit}>Cancel</button>
                <small>Press Esc to cancel | Press Enter or click outside to save</small>
              </div>
            {/if}
          {:else}
            {#if !isCategory}
              <p class="noteContent">{note.content || 'No content'}</p>
            {:else if isCategory}
              <div class="subNotes" use:dndzone={{
                items: previewChildNotes ?? childNotes,
                type: `sub-notes-${note.id}`,
                flipDurationMs: 250,
                dropTargetStyle: {},
                transformDraggedElement: transformElement,
                morphDisabled: true,
                centreDraggedOnCursor: true }}
                onconsider={handleDnd}
                onfinalize={handleDndFinalize}
              >
                {#key childNotes.map(n => n.id).join('-')}
                  {#each (previewChildNotes ?? childNotes) as child (child.id)}
                    <ComponentNote note={child} {reloadNotes} {setStatus} {notes} {noteOpenStates} />
                  {/each}
                {/key}
              </div>
            {/if}
          {/if}
        </div>
      {/if}
    </div>
  </OverlayScrollbarsComponent>
</div>

// src/components/ComponentNote.tsx
import React, { useState, useEffect, useRef } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { OverlayScrollbarsComponent } from 'overlayscrollbars-react';
import { AnimatePresence, motion } from 'framer-motion';
import { DndContext, closestCenter, KeyboardSensor, PointerSensor, useSensor, useSensors } from '@dnd-kit/core';
import { arrayMove, SortableContext, sortableKeyboardCoordinates, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';

import { useApp } from '../contexts/AppContext';

interface NoteType {
  id: number;
  title: string;
  content: string;
  tab_id: number | null;
  parent_id: number | null;
  order_id: number | null;
  note_type: string;
  created_at: string;
  updated_at: string;
}

function useOnClickOutside(ref: React.RefObject<HTMLDivElement>, handler: (event: MouseEvent) => void) {
  useEffect(() => {
    const listener = (event: MouseEvent) => {
      if (!ref.current || ref.current.contains(event.target as Node)) {
        return;
      }
      handler(event);
    };
    document.addEventListener('mousedown', listener);
    return () => {
      document.removeEventListener('mousedown', listener);
    };
  }, [ref, handler]);
}

interface SortableNoteProps {
  note: NoteType;
  reloadNotes: () => Promise<void>;
  setStatus: (message: string) => void;
}

export const SortableNote = React.memo(function SortableNote({ note, reloadNotes, setStatus }: SortableNoteProps) {

  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: note.id, transition: { duration: 200, easing: 'ease' } });

  const style = {
    transform: transform ? CSS.Transform.toString({ x: transform.x, y: transform.y, scaleX: 1, scaleY: 1}) : undefined,
    transition,
    outline: isDragging ? '#723fffd0 solid 2px' : 'none',
    zIndex: isDragging ? 1000 : 'auto',
  };

  return (
    <div ref={setNodeRef} style={style} {...attributes}>
      <Note note={note} reloadNotes={reloadNotes} setStatus={setStatus} dragHandleProps={listeners} />
    </div>
  );
});

interface NoteProps {
  note: NoteType;
  reloadNotes: () => Promise<void>;
  setStatus?: (message: string) => void;
  dragHandleProps?: any;
}

const Note = ({ note, dragHandleProps, reloadNotes, setStatus = () => {} }: NoteProps) => {
  const { notes, setNotes, childNotesByParent, noteOpenStates, setNoteOpenStates } = useApp();

  const [isEditing, setIsEditing] = useState(false);
  const [editingTitle, setEditingTitle] = useState(note.title);
  const [editingContent, setEditingContent] = useState(note.content);
  const [originalOpenState, setOriginalOpenState] = useState(false);
  const [hasSavedState, setHasSavedState] = useState(false);

  const open = noteOpenStates[note.tab_id ?? -1]?.[note.id] ?? true;
  const isCategory = note.note_type === 'categorical';
  const isOpen = isEditing || open;

  const childNotes = childNotesByParent.get(note.id) ?? [];

  useEffect(() => {
    if (!note.tab_id) return;

    setNoteOpenStates(prev => {
      const tabState = prev[note.tab_id!] ?? {}
      const validIds = new Set(notes.map(n => n.id));

      const cleaned = Object.fromEntries(
        Object.entries(tabState).filter(([id]) => validIds.has(Number(id)))
      );

      return {
        ...prev,
        [note.tab_id!]: cleaned
      };
    });
  }, [notes]);

  const editRef = useRef<HTMLDivElement>(null);
  useOnClickOutside(editRef as React.RefObject<HTMLDivElement>, () => {
    if (isEditing) saveEdit();
  });

  const handleDoubleClick = () => {
    setOriginalOpenState(open);
    setHasSavedState(true);
    setIsEditing(true);
    setEditingTitle(note.title);
    setEditingContent(note.content);
  };

  const toggle = () => {
    setNoteOpenStates((prev: Record<number, Record<number, boolean>>) => ({ ...prev, [note.tab_id!]: { ...(prev[note.tab_id!] ?? {}), [note.id]: !open }}));
  };

  const addChild = async () => {
    try {
      const newNote: NoteType = await invoke('create_note', { title: 'Untitled', content: '', tabId: note.tab_id, noteType: 'basic', parentId: note.id });
      setNotes((prev: NoteType[]) => [ ...prev, newNote]);
      setNoteOpenStates((prev: Record<number, Record<number, boolean>>) => ({ ...prev, [note.tab_id!]: { ...(prev[note.tab_id!] ?? {}), [note.id]: true }}));

      setStatus('Added sub-note successfully');
    } catch (error) {
      console.error(error);
      setStatus(`Failed to add sub-note: ${error}`);
    }
  };

  const saveEdit = async () => {
    try {
      await invoke('update_note', { id: note.id, title: editingTitle, content: editingContent || '' });
      setIsEditing(false);
      setNoteOpenStates((prev: Record<number, Record<number, boolean>>) => ({ ...prev, [note.tab_id!]: { ...(prev[note.tab_id!] ?? {}), [note.id]: true }}));

      setNotes(prev => prev.map(n => n.id === note.id ? { ...n, title: editingTitle, content: editingContent, updated_at: new Date().toISOString() } : n));
      setStatus(`Updated note ${note.title} successfully`);
    } catch (error) {
      console.error(error);
      setStatus(`Failed to update ${note.title} note: ${error}`);
    }
  };

  const cancelEdit = () => {
    setIsEditing(false);
    if (hasSavedState) {
      setNoteOpenStates((prev: Record<number, Record<number, boolean>>) => ({ ...prev, [note.tab_id!]: { ...(prev[note.tab_id!] ?? {}), [note.id]: originalOpenState }}));
      setHasSavedState(false);
    }
  };

  const removeNote = async () => {
    try {
      await invoke('delete_note', { id: note.id });
      await reloadNotes();
      setStatus(`Deleted note ${note.title} successfully`);
    } catch(error) {
      console.error(error);
      setStatus(`Failed to delete ${note.title} successfully`);
    }
  };

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 5 } }),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );

  const handleDragEnd = async (event: any) => {
    const { active, over } = event;
    if (active.id !== over?.id) {
      const oldIndex = childNotes.findIndex((n) => n.id === active.id);
      const newIndex = childNotes.findIndex((n) => n.id === over.id);
      const newOrder = arrayMove(childNotes, oldIndex, newIndex);
      setNotes((prev: NoteType[]) => {
        const updated = prev.map((n) => {
          if (n.parent_id === note.id) {
            const found = newOrder.find((c) => c.id === n.id);
            if (found) {
              return { ...n, order_id: newOrder.indexOf(found) + 1 };
            }
          }
          return n;
        });
        return updated;
      });

      const orderedIds = newOrder.map((n) => n.id);
      try {
        await invoke('reorder_notes', { noteIds: orderedIds });
        setStatus('Sub-notes reordered successfully');
      } catch (error) {
        console.error(error)
        setStatus(`Failed to reorder sub-notes: ${error}`);
        await reloadNotes();
      }
    }
  };

  return (
    <div ref={editRef} className={`note ${isCategory ? 'category' : ''} ${isEditing ? 'editing' : ''}`} onDoubleClick={(e) => { e.stopPropagation(); handleDoubleClick(); }} role="article">
      <div id="noteTitleBox">
        <div className="noteDragHandle" {...dragHandleProps}>
          Drag
        </div>
        <small>Last edited: {note.updated_at}</small>
        <small>Note ID: {note.id}</small>
        <small>Tab ID: {note.tab_id}</small>
        <small>Order ID: {note.order_id}</small>
        <div id="noteControls">
          {isCategory ? (
            <>
              <button onClick={toggle} disabled={isEditing}>
                {open ? 'Hide' : 'Show'}
              </button>
              <button onClick={addChild}>Add Child</button>
              <button onClick={() => setIsEditing(true)} disabled={isEditing}>Edit</button>
              <button onClick={removeNote}>Delete</button>
            </>
          ) : (
            <>
              <button onClick={toggle} disabled={isEditing}>
                {open ? 'Hide' : 'Show'}
              </button>
              <button onClick={() => setIsEditing(true)} disabled={isEditing}>Edit</button>
              <button onClick={removeNote}>Delete</button>
            </>
          )}
        </div>
        {isEditing ? (
          <input
            value={editingTitle}
            onChange={(e) => setEditingTitle(e.target.value)}
            placeholder="Title | Enter to save"
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                saveEdit();
              } else if (e.key === 'Escape') {
                cancelEdit();
              }
            }}
          />
        ) : (
          <h3 className="noteTitle">{note.title || 'Untitled'}</h3>
        )}
      </div>

      <OverlayScrollbarsComponent options={{ scrollbars: { autoHide: 'move', autoHideDelay: 800, theme: 'os-theme-dark' }, overflow: { x: 'hidden' } }}>
        <div id="noteContentOuter">
          <AnimatePresence>
            {isOpen && (
              <motion.div
                initial={{ height: 0 }}
                animate={{ height: 'auto' }}
                exit={{ height: 0 }}
                transition={{ duration: 0.4, ease: 'easeInOut' }}
                style={{ overflow: 'hidden' }}
              >
                {isEditing ? (
                  <>
                    {!isCategory && (
                      <textarea
                        value={editingContent}
                        onChange={(e) => setEditingContent(e.target.value)}
                        placeholder="Enter to save | Shift+Enter for new line | Esc to cancel"
                        rows={16}
                        onKeyDown={(e) => {
                          if (e.key === 'Enter' && !e.shiftKey) {
                            e.preventDefault();
                            saveEdit();
                          } else if (e.key === 'Escape') {
                            cancelEdit();
                          }
                        }}
                      />
                    )}
                    <div className="edit-actions">
                      <button onClick={saveEdit}>Save</button>
                      <button onClick={cancelEdit}>Cancel</button>
                      <small>Press Esc to cancel | Press Enter or click outside to save</small>
                    </div>
                  </>
                ) : (
                  <>
                    {!isCategory && <p className="noteContent">{note.content || 'No content'}</p>}
                    {isCategory && (
                      <DndContext
                        sensors={sensors}
                        collisionDetection={closestCenter}
                        onDragEnd={handleDragEnd}
                      >
                        <SortableContext items={childNotes.map((n) => n.id)} strategy={verticalListSortingStrategy}>
                          <div className="subNotes">
                            {childNotes.map((child) => (
                              <SortableNote key={child.id} note={child} reloadNotes={reloadNotes} setStatus={setStatus} />
                            ))}
                          </div>
                        </SortableContext>
                      </DndContext>
                    )}
                  </>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </OverlayScrollbarsComponent>
    </div>
  );
};

export default React.memo(Note);
